/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/beverage/addBeverage` | `/beverage/addBeverage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/beverage` | `/beverage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/beverageSize/addBeverageSize` | `/beverageSize/addBeverageSize`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/beverageSize` | `/beverageSize`; params?: Router.UnknownInputParams; } | { pathname: `/order/createOrder`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/beverage/addBeverage` | `/beverage/addBeverage`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/beverage` | `/beverage`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/beverageSize/addBeverageSize` | `/beverageSize/addBeverageSize`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/beverageSize` | `/beverageSize`; params?: Router.UnknownOutputParams; } | { pathname: `/order/createOrder`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/beverage/addBeverage${`?${string}` | `#${string}` | ''}` | `/beverage/addBeverage${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/beverage${`?${string}` | `#${string}` | ''}` | `/beverage${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/beverageSize/addBeverageSize${`?${string}` | `#${string}` | ''}` | `/beverageSize/addBeverageSize${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/beverageSize${`?${string}` | `#${string}` | ''}` | `/beverageSize${`?${string}` | `#${string}` | ''}` | `/order/createOrder${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/beverage/addBeverage` | `/beverage/addBeverage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/beverage` | `/beverage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/beverageSize/addBeverageSize` | `/beverageSize/addBeverageSize`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/beverageSize` | `/beverageSize`; params?: Router.UnknownInputParams; } | { pathname: `/order/createOrder`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
